# --- !Ups

CREATE TABLE address (
  ID BIGINT NOT NULL PRIMARY KEY,
  ZIP_CODE VARCHAR(255),
  CITY VARCHAR(255),
  STREET VARCHAR(255),
  HOUSE_NUMBER VARCHAR(255)
);

# --- !Downs

DROP TABLE IF EXISTS address;