# --- !Ups

CREATE TABLE employee (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255),
  ADDRESS_ID BIGINT,
  DEPARTMENT_ID BIGINT
);

# --- !Downs

DROP TABLE IF EXISTS employee;